import { DeviceModel, DeviceCategory, createDeviceModel } from '../domain/entities/device-model';

/**
 * Test data for device models
 * Realistic sample data for development and testing
 */
export const testDeviceModels: DeviceModel[] = [
  createDeviceModel({
    id: 'laptop-dell-xps-13',
    brand: 'Dell',
    model: 'XPS 13',
    category: DeviceCategory.Laptop,
    description: 'Ultra-portable 13-inch laptop with Intel Core i7 processor, 16GB RAM, and 512GB SSD. Perfect for students who need power and portability.',
    specifications: {
      'Processor': 'Intel Core i7-1165G7',
      'RAM': '16GB DDR4',
      'Storage': '512GB NVMe SSD',
      'Display': '13.4" FHD+ (1920x1200)',
      'Graphics': 'Intel Iris Xe',
      'Battery': '52Wh',
      'Weight': '1.27kg',
      'OS': 'Windows 11 Pro',
    },
    imageUrl: 'https://example.com/images/dell-xps-13.jpg',
    featured: true,
  }),
  createDeviceModel({
    id: 'laptop-macbook-air-m2',
    brand: 'Apple',
    model: 'MacBook Air M2',
    category: DeviceCategory.Laptop,
    description: 'Apple Silicon powered laptop with M2 chip, 8GB unified memory, and 256GB storage. Ideal for creative work and development.',
    specifications: {
      'Processor': 'Apple M2',
      'RAM': '8GB Unified Memory',
      'Storage': '256GB SSD',
      'Display': '13.6" Liquid Retina (2560x1664)',
      'Graphics': '8-core GPU',
      'Battery': 'Up to 18 hours',
      'Weight': '1.24kg',
      'OS': 'macOS Ventura',
    },
    imageUrl: 'https://example.com/images/macbook-air-m2.jpg',
    featured: true,
  }),
  createDeviceModel({
    id: 'laptop-lenovo-thinkpad-x1',
    brand: 'Lenovo',
    model: 'ThinkPad X1 Carbon',
    category: DeviceCategory.Laptop,
    description: 'Business-grade laptop with Intel Core i5, 8GB RAM, and 256GB SSD. Durable and reliable for academic work.',
    specifications: {
      'Processor': 'Intel Core i5-1135G7',
      'RAM': '8GB DDR4',
      'Storage': '256GB NVMe SSD',
      'Display': '14" FHD (1920x1080)',
      'Graphics': 'Intel Iris Xe',
      'Battery': '57Wh',
      'Weight': '1.13kg',
      'OS': 'Windows 11 Pro',
    },
    imageUrl: 'https://example.com/images/thinkpad-x1.jpg',
    featured: false,
  }),
  createDeviceModel({
    id: 'tablet-ipad-air',
    brand: 'Apple',
    model: 'iPad Air',
    category: DeviceCategory.Tablet,
    description: '10.9-inch tablet with M1 chip, perfect for note-taking, reading, and creative projects.',
    specifications: {
      'Processor': 'Apple M1',
      'RAM': '8GB',
      'Storage': '64GB',
      'Display': '10.9" Liquid Retina (2360x1640)',
      'Battery': 'Up to 10 hours',
      'Weight': '461g',
      'OS': 'iPadOS 16',
    },
    imageUrl: 'https://example.com/images/ipad-air.jpg',
    featured: true,
  }),
  createDeviceModel({
    id: 'tablet-surface-pro',
    brand: 'Microsoft',
    model: 'Surface Pro 9',
    category: DeviceCategory.Tablet,
    description: '2-in-1 tablet/laptop with Intel Core i5, 8GB RAM, and detachable keyboard. Versatile for both tablet and laptop use.',
    specifications: {
      'Processor': 'Intel Core i5-1235U',
      'RAM': '8GB LPDDR5',
      'Storage': '256GB SSD',
      'Display': '13" PixelSense (2880x1920)',
      'Graphics': 'Intel Iris Xe',
      'Battery': 'Up to 15.5 hours',
      'Weight': '879g',
      'OS': 'Windows 11',
    },
    imageUrl: 'https://example.com/images/surface-pro.jpg',
    featured: false,
  }),
  createDeviceModel({
    id: 'camera-canon-eos-r6',
    brand: 'Canon',
    model: 'EOS R6',
    category: DeviceCategory.Camera,
    description: 'Full-frame mirrorless camera with 20MP sensor, 4K video, and in-body image stabilization. Perfect for photography and videography projects.',
    specifications: {
      'Sensor': '20.1MP Full-Frame CMOS',
      'Video': '4K UHD 60p',
      'ISO': '100-102400',
      'Stabilization': '5-axis IBIS',
      'Autofocus': 'Dual Pixel CMOS AF II',
      'Battery': 'LP-E6NH',
      'Weight': '680g',
    },
    imageUrl: 'https://example.com/images/canon-eos-r6.jpg',
    featured: true,
  }),
  createDeviceModel({
    id: 'camera-sony-a7iii',
    brand: 'Sony',
    model: 'Alpha A7 III',
    category: DeviceCategory.Camera,
    description: 'Full-frame mirrorless camera with 24MP sensor and excellent low-light performance. Great for professional photography work.',
    specifications: {
      'Sensor': '24.2MP Full-Frame Exmor R CMOS',
      'Video': '4K UHD 30p',
      'ISO': '100-51200',
      'Stabilization': '5-axis IBIS',
      'Autofocus': '693 phase-detection points',
      'Battery': 'NP-FZ100',
      'Weight': '650g',
    },
    imageUrl: 'https://example.com/images/sony-a7iii.jpg',
    featured: false,
  }),
  createDeviceModel({
    id: 'phone-iphone-14',
    brand: 'Apple',
    model: 'iPhone 14',
    category: DeviceCategory.MobilePhone,
    description: 'Latest iPhone with A15 Bionic chip, 128GB storage, and excellent camera system. Suitable for mobile development testing.',
    specifications: {
      'Processor': 'A15 Bionic',
      'RAM': '6GB',
      'Storage': '128GB',
      'Display': '6.1" Super Retina XDR',
      'Camera': 'Dual 12MP',
      'Battery': 'Up to 20 hours video playback',
      'Weight': '172g',
      'OS': 'iOS 16',
    },
    imageUrl: 'https://example.com/images/iphone-14.jpg',
    featured: false,
  }),
  createDeviceModel({
    id: 'keyboard-logitech-mx',
    brand: 'Logitech',
    model: 'MX Keys',
    category: DeviceCategory.Keyboard,
    description: 'Wireless keyboard with backlit keys, multi-device connectivity, and ergonomic design. Perfect for extended typing sessions.',
    specifications: {
      'Connectivity': 'Bluetooth, USB Receiver',
      'Battery': 'Up to 5 months',
      'Backlight': 'Yes',
      'Keys': '105 keys',
      'Weight': '810g',
    },
    imageUrl: 'https://example.com/images/logitech-mx-keys.jpg',
    featured: false,
  }),
  createDeviceModel({
    id: 'mouse-logitech-mx-master',
    brand: 'Logitech',
    model: 'MX Master 3',
    category: DeviceCategory.Mouse,
    description: 'Wireless ergonomic mouse with precision tracking, multi-device support, and customizable buttons. Great for design work.',
    specifications: {
      'Connectivity': 'Bluetooth, USB Receiver',
      'Battery': 'Up to 70 days',
      'DPI': '4000 DPI',
      'Buttons': '7 programmable buttons',
      'Weight': '141g',
    },
    imageUrl: 'https://example.com/images/mx-master-3.jpg',
    featured: false,
  }),
  createDeviceModel({
    id: 'charger-usb-c-65w',
    brand: 'Anker',
    model: '65W USB-C Charger',
    category: DeviceCategory.Charger,
    description: 'Fast-charging USB-C power adapter with 65W output. Compatible with laptops, tablets, and phones.',
    specifications: {
      'Output': '65W',
      'Ports': '1x USB-C',
      'Input': '100-240V AC',
      'Weight': '120g',
    },
    imageUrl: 'https://example.com/images/anker-65w.jpg',
    featured: false,
  }),
];

